import Vue from 'vue'
import { Scrollbar, Button, Container, Header, Aside, Main, Submenu, MenuItemGroup, MenuItem, Menu, Breadcrumb, Col, Row, Dialog, Pagination, Card, Input, Table, TableColumn } from 'element-ui'

Vue.use(Scrollbar)
Vue.use(Button)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Submenu)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Breadcrumb)
Vue.use(Card)
Vue.use(Col)
Vue.use(Row)
Vue.use(Input)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Pagination)
Vue.use(Dialog)
